-- Supabase Schema Migration
-- Execute this in the Supabase SQL Editor

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'attendant',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Requests Table
CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  protocol TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  citizen_name TEXT,
  citizen_phone TEXT,
  address TEXT,
  details TEXT,
  photo_url TEXT,
  status TEXT DEFAULT 'Pendente',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Routes Table
CREATE TABLE IF NOT EXISTS routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  neighborhoods TEXT,
  days TEXT,
  hours TEXT,
  observations TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Ecopoints Table
CREATE TABLE IF NOT EXISTS ecopoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  hours TEXT,
  materials TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Settings Table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- 6. Chat Sessions Table
CREATE TABLE IF NOT EXISTS chat_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  citizen_phone TEXT UNIQUE NOT NULL,
  citizen_name TEXT,
  status TEXT DEFAULT 'bot',
  last_message_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  current_state TEXT DEFAULT 'START',
  temp_data TEXT,
  whatsapp_number_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES chat_sessions(id) ON DELETE CASCADE,
  sender TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Default Settings
INSERT INTO settings (key, value) VALUES 
('welcome_message', '👋 Bem-vindo ao atendimento virtual da Secretaria Municipal de Serviços Urbanos (SEURB) – Prefeitura de Ananindeua!'),
('off_hours_message', '⏰ Nosso atendimento é de segunda a sexta-feira (exceto feriados), de 8h às 15h.'),
('bot_instructions', 'Você é o assistente virtual da SEURB Ananindeua. Ajude os cidadãos com coleta de lixo, entulho e limpeza de bueiros.')
ON CONFLICT (key) DO NOTHING;

-- Default Admin
INSERT INTO users (name, email, role) 
VALUES ('Tiago', 'tiago.angelica@gmail.com', 'manager')
ON CONFLICT (email) DO NOTHING;
